import './globals.css'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
